apiVersion: v1
kind: ConfigMap
metadata:
  name: extra-nats-values
data:
  values.yaml: |
    auth:
      enabled: true
      user: ''
      token: $NATS_AUTH_TOKEN
    client:
      service:
        type: LoadBalancer
    extraEnvVarsSecret: nats-env-vars-secret
