apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nats-env-vars-secret
  namespace: wkp-gitops-repo-broker
spec:
  encryptedData:
    NATS_AUTH_TOKEN: AgBwojFcgOnEEiRg5fwRLEy+IkaByFN5eXCTFTO0pKDw0+qxZE6+FlmeZm5Jv6eNDHZf5J78oGh2Iq79KmL57ko9sCqKDPjFPtzGd4hjkdTX3LRQrgfc/ovmj8+80S3m/+VkOhccWwUCfwBYQEUlCmkuhzfabxYwJVE9R69ZhhIvJMTTZ3p3882NqVKWO+snYd8RoclfpHgllUHIrUs2Ug/el63ZAaF7c9l4kzLGbrLiPnuO6lv9xexX/Mm8MI63gqh3u4lGtF6P3pm3l7VHg12zsJCNpg9N5tAjGCvTcMiZltfGrcy9WFoCpz5d6aAszSFllUiFUKS3WBgF4U2eeCiS2E7uVoE3bz/TEhJKWprpBZhr5y1kCn3azO8Wzze0F1pKKYXvbd/oHNbWSosBPcBN+Z6+y9ghcSdi6AksCXtm90yneiVpOJUSSz06gqYfNxxUzFml3YwfHTU1vP4L93EBTDkccWQnz6LOvBZr5WbBxZMaISdxZ/RC10OWw1ZHzhKkMZvttcG05QMuuHCiQAotATAQWtB/BzEe/75m0KVQOPTjHMvlzJBx4LG22lFS0bW9YTLwmAbhtRabN96YAwbyX8WhV0q0AhzqBR2Hx0FUBgjrJiVltSDlGR+kbh5dFD/XtutDjAFEgp6GUP25+zM8+cI+KqijJk6ZXL7CFxGHpBVst0/Mg/23Ek8O03WnuiEnbRH7+IofY5HeKxaBVI08y6c/Xg==
  template:
    metadata:
      creationTimestamp: null
      name: nats-env-vars-secret
      namespace: wkp-gitops-repo-broker
    type: Opaque
status: {}

