apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: image-pull-information
  namespace: weavek8sops
spec:
  encryptedData:
    password: AgCPbczhdDC0VRxs2VTnU3ZxJrSZ1qc5fhJ6KY/jzrlRhFg1H6Pvbw/0KClmJpfIu+GlWlMnISrmeozHcfyV0wLnWj4LVS7gwYy395L0SNQiWkA9pimyVBf/iSUxEqdjKYztUH7mEv9nMy/Jyr1gKlz5X/rTgfQsjlXj1zD2e09MnF+4zyd2krK57SO6ewzockW7m5G3QzbSldt0HIMXvpw/GVSS2XfPcpmem1fRumdbo/jTRwzggeAwVQ4JHTp+CHq/0VpVXhwA653pK9b5nc0FCM1ejPUfeN6UD1Zj+qnqgAa3wFYBb6FHeARkcLx8iPJzQcRtTPGzl66hZcgNRe7uCpEk2MelV7JBRw20ZMC7sFDf6+3vcFD9Wy6rkJsyEWhEjQ6Df2Tpu70FBC1rrkcu6zJbvPeKPhKxpCU7aaD0Nu1xPAlQ935EQzzqXNrBjgfNNs7m+xjZ18dhUtqVeacBusqMlYBme+iUKs6FGn8/uiV3dh+NArQRrg2tLc0ScTZFyhSRk1/VWP3AkK1kJqEohhNeABCR3EzF4ZNsam3QT0DnnbGZxAkjXd9T6ErwJeKhuZacfmCSLUX23snwnEv2wHgapIfeDoNxxWmFcNlE8gNbiggGMOTo6LDvgpNiLq/z6nhP54PMaBbo9GowOOUjWPkbGuZGAcR8Ah9rKw4A+1G4mCLx15onMlie/Y9cuaMJ5qC9gw9AADg=
    username: AgBX60ZB7S2zWeqLPKaXuj69QDc16H7uckDjm2huYkL1IOfy9Eeyl59HzIBQAE8JBfJKxJedVqEVUMbA5cpMGfDcBQKBxvb37QyJUauEGQKb99BvQEBuvRzm26COCGnYGUtzsVxGGr1eTbMbiqb8SG2wRbIauoxJXA/AQ4F17v2RDTINEbA8GC46cxsbO6LWVafh2eN51A51lZbdblfIQTMDQe6UI1Dnnl6406eoWkOzch24aKNDMAzBq/k+bZNZ7wFBw9QKMbqqrayJ1ttHap1s/KOppw/Yu0g3T1gwxKoGzxpC5d3cDEe67XemE68tw0dEwqccyd4jV2kOhp66gOIxmuvkOx1hTypfv5VBlpfad8mH1csJPDMolQAPUO0QkJEsXJgkx8Iuns5+3NxkKWydqBJMWWOak5XsZREoXci64REkkyDKnmNXywBMY4tRsVVhwu03PXqZFKDzknaZtvaPwcxSg1kXqs+nVrTiofd0CKb5cUTNWdCIszkmjlleSpD6UfJthRwWYiACD1pcBH3TTUrRu8j2AiexYSBcSx9SeZvVDzyI/+Uv7N28VvgC4vDO1kInabeCEMojkS4Ueb4sqazFlx6Nh3WD6rB6mkAjfcZs3atU6XRjptLM0/57lbg2t7ORRn4N9eY1pStJJCD+x+Cz+VIfO6S9Zzzn7jVrXuXnkwnvd3wOZ5RnfIHThIL7KWcwknA5xxM=
  template:
    metadata:
      creationTimestamp: null
      name: image-pull-information
      namespace: weavek8sops
    type: Opaque
status: {}

