# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mccp-volume
#   namespace: wkp-gitops-repo-broker
# spec:
#   storageClassName: default
#   resources:
#     requests:
#       storage: 100G
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
